import { expect, test } from "@playwright/test";
import { tmpdir } from "node:os";
import path from "node:path";

for (const width of [1440, 430]) {
  test(`manual writing review, revision, backup and account isolation (${width})`, async ({ page }) => {
    await page.setViewportSize({ width, height: 932 });
    const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    page.on("console", message => { if (message.type() === "error") errors.push(message.text()); });
    await page.goto("/");
    await page.evaluate(() => localStorage.setItem("pet-vocab-e2e-session", "RUN1"));
    await page.reload();
    await page.getByRole("button", { name: "写作", exact: true }).click();
    await expect(page.getByRole("heading", { name: "写作练习", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "开始一篇新练习" }).click();
    await page.getByLabel("我的审题记录").fill("时间、地点、活动、原因、带什么");
    await page.getByLabel("作文原稿", { exact: true }).fill("Dear Alex, It not far from my house. Bring you water bottle.");
    await page.getByLabel("实际用时（分钟）").fill("20");
    await page.getByLabel("添加手写照片（最多两张）").setInputFiles({ name: "handwriting.png", mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aZ1sAAAAASUVORK5CYII=", "base64") });
    await expect(page.getByAltText("手写原稿第 1 页")).toBeVisible();
    await page.getByRole("button", { name: "提交并保留原稿" }).click();
    await expect(page.getByLabel("作文原稿", { exact: true })).toHaveAttribute("readonly", "");
    const download = page.waitForEvent("download");
    await page.getByRole("button", { name: "导出点评材料", exact: true }).click();
    expect((await download).suggestedFilename()).toMatch(/PET-writing-.*\.txt/);
    await page.getByText("查看可复制的点评材料", { exact: true }).click();
    const material = await page.getByLabel("可复制的点评材料").inputValue();
    const template = JSON.parse(material.slice(material.indexOf('{\n  "kind"')));
    await page.getByLabel("导入点评 JSON").setInputFiles({ name: "wrong.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify({ ...template, attemptId: "wrong" })) });
    await expect(page.getByRole("alert")).toContainText("不属于当前作文");
    await page.getByLabel("导入点评 JSON").setInputFiles({ name: "feedback.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify({ ...template, feedback: "请补上 is，并把 you 改成 your。", revisionFeedback: "" })) });
    await expect(page.getByLabel("原稿点评", { exact: true })).toHaveValue("请补上 is，并把 you 改成 your。");
    await page.getByLabel("我的修改稿", { exact: false }).fill("Dear Alex, It is not far from my house. Bring your water bottle.");
    await page.getByLabel("修改稿复查点评").fill("这两处已修正，请再补充见面时间。");
    await expect(page.getByText("已保存到本机", { exact: true })).toBeVisible();
    await page.reload();
    await page.getByRole("button", { name: "写作", exact: true }).click();
    await expect(page.getByLabel("原稿点评", { exact: true })).toHaveValue("请补上 is，并把 you 改成 your。");
    await expect(page.getByLabel("作文原稿", { exact: true })).toHaveValue("Dear Alex, It not far from my house. Bring you water bottle.");
    await expect(page.getByAltText("手写原稿第 1 页")).toBeVisible();
    await expect(page.getByLabel("我的修改稿", { exact: false })).toHaveValue(/It is not far/);
    const backupDownload = page.waitForEvent("download");
    await page.getByRole("button", { name: "导出写作备份（含照片）" }).click();
    const backup = await backupDownload;
    await page.getByLabel("恢复写作备份").setInputFiles((await backup.path())!);
    await expect(page.getByRole("alert")).toContainText("已合并恢复");
    await expect(page.getByLabel("已有写作记录").locator("option")).toHaveCount(1);
    await page.getByLabel("原稿点评", { exact: true }).scrollIntoViewIfNeeded();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await expect(page.locator("vite-error-overlay")).toHaveCount(0);
    await page.screenshot({ path: path.join(tmpdir(), `pet-writing-${width}.png`), fullPage: false });
    await page.getByRole("button", { name: "我的", exact: true }).click();
    await page.getByRole("button", { name: "退出登录" }).click();
    await page.getByLabel("用户名").fill("RUN2");
    await page.locator("#pet-password").fill("e2e-test-only-password");
    await page.getByRole("button", { name: "登录", exact: true }).click();
    await page.getByRole("button", { name: "写作", exact: true }).click();
    await expect(page.getByLabel("已有写作记录")).toHaveCount(0);
    await page.getByLabel("恢复写作备份").setInputFiles((await backup.path())!);
    await expect(page.getByRole("alert")).toContainText("当前账号");
    expect(errors).toEqual([]);
  });
}

test("a stale tab cannot overwrite writing saved by another tab", async ({ page, context }) => {
  await page.goto("/");
  await page.evaluate(() => localStorage.setItem("pet-vocab-e2e-session", "RUN1"));
  await page.reload();
  await page.getByRole("button", { name: "写作", exact: true }).click();
  await page.getByRole("button", { name: "开始一篇新练习" }).click();
  await expect(page.getByText("已保存到本机", { exact: true })).toBeVisible();
  const second = await context.newPage();
  await second.goto("/");
  await second.getByRole("button", { name: "写作", exact: true }).click();
  await expect(second.getByLabel("作文原稿", { exact: true })).toBeVisible();
  await page.getByLabel("作文原稿", { exact: true }).fill("The first tab has new work.");
  await expect(page.getByText("已保存到本机", { exact: true })).toBeVisible();
  await second.getByLabel("作文原稿", { exact: true }).fill("The second tab must not replace it.");
  await expect(second.getByRole("status")).toContainText("其他标签页已修改");
  await page.reload();
  await page.getByRole("button", { name: "写作", exact: true }).click();
  await expect(page.getByLabel("作文原稿", { exact: true })).toHaveValue("The first tab has new work.");
  await second.close();
});
