export interface PetWord {
  id: number;
  category: PetCategory;
  word: string;
  ipa: string;
  partOfSpeech: string;
  meaning: string;
  syllables: string[];
  stress: string;
  phonics: string;
  example: string;
  translation: string;
}

export type PetCategory = "扩展词库" | "学习与能力" | "旅行与活动" | "日常交流" | "生活与环境" | "感受与责任";

export const PET_WORDS: PetWord[] = [
  {
    id: 1,
    category: "学习与能力",
    word: "ability",
    ipa: "/əˈbɪləti/",
    partOfSpeech: "n.",
    meaning: "能力；才能",
    syllables: ["a", "bil", "i", "ty"],
    stress: "重音在第二音节 bil",
    phonics: "开头 a 常读弱音 /ə/，字母 i 在重读闭音节中读 /ɪ/。",
    example: "She has the ability to learn quickly.",
    translation: "她有快速学习的能力。",
  },
  {
    id: 2,
    category: "学习与能力",
    word: "achieve",
    ipa: "/əˈtʃiːv/",
    partOfSpeech: "v.",
    meaning: "实现；取得",
    syllables: ["a", "chieve"],
    stress: "重音在第二音节 chieve",
    phonics: "ch 读 /tʃ/，ie 在这里读长音 /iː/。",
    example: "You can achieve your goal with daily practice.",
    translation: "坚持每天练习，你就能实现目标。",
  },
  {
    id: 3,
    category: "旅行与活动",
    word: "adventure",
    ipa: "/ədˈventʃə/",
    partOfSpeech: "n.",
    meaning: "冒险；奇遇",
    syllables: ["ad", "ven", "ture"],
    stress: "重音在第二音节 ven",
    phonics: "ture 在词尾常读 /tʃə/，首音节通常弱读。",
    example: "Our camping trip became a real adventure.",
    translation: "我们的露营旅行成了一次真正的冒险。",
  },
  {
    id: 4,
    category: "日常交流",
    word: "although",
    ipa: "/ɔːlˈðəʊ/",
    partOfSpeech: "conj.",
    meaning: "虽然；尽管",
    syllables: ["al", "though"],
    stress: "重音在第二音节 though",
    phonics: "th 在这里发浊辅音 /ð/，ough 组合读 /əʊ/。",
    example: "Although it was raining, we walked to school.",
    translation: "虽然下雨了，我们还是步行去学校。",
  },
  {
    id: 5,
    category: "日常交流",
    word: "announce",
    ipa: "/əˈnaʊns/",
    partOfSpeech: "v.",
    meaning: "宣布；通知",
    syllables: ["an", "nounce"],
    stress: "重音在第二音节 nounce",
    phonics: "ou 在这里读双元音 /aʊ/，词尾 ce 读 /s/。",
    example: "The teacher will announce the results tomorrow.",
    translation: "老师明天会公布结果。",
  },
  {
    id: 6,
    category: "生活与环境",
    word: "available",
    ipa: "/əˈveɪləbəl/",
    partOfSpeech: "adj.",
    meaning: "可获得的；有空的",
    syllables: ["a", "vail", "a", "ble"],
    stress: "重音在第二音节 vail",
    phonics: "ai 读 /eɪ/，词尾 able 常弱读为 /əbəl/。",
    example: "Is this book available in the library?",
    translation: "图书馆里有这本书吗？",
  },
  {
    id: 7,
    category: "感受与责任",
    word: "behaviour",
    ipa: "/bɪˈheɪvjə/",
    partOfSpeech: "n.",
    meaning: "行为；举止",
    syllables: ["be", "hav", "iour"],
    stress: "重音在第二音节 hav",
    phonics: "字母组合 avi 在这里形成 /eɪvj/，英式拼写保留 u。",
    example: "Good behaviour makes the classroom pleasant.",
    translation: "良好的行为会让教室更愉快。",
  },
  {
    id: 8,
    category: "生活与环境",
    word: "borrow",
    ipa: "/ˈbɒrəʊ/",
    partOfSpeech: "v.",
    meaning: "借入",
    syllables: ["bor", "row"],
    stress: "重音在第一音节 bor",
    phonics: "第一个 o 在英音中读 /ɒ/，词尾 ow 读 /əʊ/。",
    example: "May I borrow your dictionary for a minute?",
    translation: "我可以借一下你的词典吗？",
  },
  {
    id: 9,
    category: "旅行与活动",
    word: "celebrate",
    ipa: "/ˈseləbreɪt/",
    partOfSpeech: "v.",
    meaning: "庆祝",
    syllables: ["cel", "e", "brate"],
    stress: "重音在第一音节 cel",
    phonics: "c 在 e 前读 /s/，词尾 a_e 形成长音 /eɪ/。",
    example: "We will celebrate her birthday on Saturday.",
    translation: "我们将在星期六庆祝她的生日。",
  },
  {
    id: 10,
    category: "生活与环境",
    word: "comfortable",
    ipa: "/ˈkʌmftəbəl/",
    partOfSpeech: "adj.",
    meaning: "舒适的；自在的",
    syllables: ["com", "fort", "a", "ble"],
    stress: "重音在第一音节 com",
    phonics: "自然语流中常省略中间元音，读成三个主要音节。",
    example: "These shoes are light and comfortable.",
    translation: "这双鞋既轻便又舒适。",
  },
  {
    id: 11,
    category: "学习与能力",
    word: "communicate",
    ipa: "/kəˈmjuːnɪkeɪt/",
    partOfSpeech: "v.",
    meaning: "交流；传达",
    syllables: ["com", "mu", "ni", "cate"],
    stress: "重音在第二音节 mu",
    phonics: "u 在这里读 /juː/，词尾 ate 读 /eɪt/。",
    example: "We communicate with our friends online.",
    translation: "我们在网上和朋友交流。",
  },
  {
    id: 12,
    category: "旅行与活动",
    word: "competition",
    ipa: "/ˌkɒmpəˈtɪʃən/",
    partOfSpeech: "n.",
    meaning: "比赛；竞争",
    syllables: ["com", "pe", "ti", "tion"],
    stress: "主重音在第三音节 ti",
    phonics: "tion 在词尾通常读 /ʃən/。",
    example: "Our team entered a science competition.",
    translation: "我们队参加了一场科学竞赛。",
  },
  {
    id: 13,
    category: "日常交流",
    word: "decide",
    ipa: "/dɪˈsaɪd/",
    partOfSpeech: "v.",
    meaning: "决定",
    syllables: ["de", "cide"],
    stress: "重音在第二音节 cide",
    phonics: "c 在 i 前读 /s/，i_e 形成长音 /aɪ/。",
    example: "We need to decide where to meet.",
    translation: "我们需要决定在哪里见面。",
  },
  {
    id: 14,
    category: "生活与环境",
    word: "environment",
    ipa: "/ɪnˈvaɪrənmənt/",
    partOfSpeech: "n.",
    meaning: "环境",
    syllables: ["en", "vi", "ron", "ment"],
    stress: "重音在第二音节 vi",
    phonics: "i 在重读音节中读 /aɪ/，词尾 ment 读 /mənt/。",
    example: "Cycling is better for the environment.",
    translation: "骑自行车对环境更好。",
  },
  {
    id: 15,
    category: "感受与责任",
    word: "experience",
    ipa: "/ɪkˈspɪəriəns/",
    partOfSpeech: "n./v.",
    meaning: "经历；体验",
    syllables: ["ex", "pe", "ri", "ence"],
    stress: "重音在第二音节 pe",
    phonics: "词首 ex 在这里读 /ɪks/，词尾 ence 读 /iəns/。",
    example: "Working in the café was a useful experience.",
    translation: "在咖啡馆工作是一段有用的经历。",
  },
  {
    id: 16,
    category: "生活与环境",
    word: "favourite",
    ipa: "/ˈfeɪvərɪt/",
    partOfSpeech: "adj./n.",
    meaning: "最喜欢的；最爱",
    syllables: ["fa", "vour", "ite"],
    stress: "重音在第一音节 fa",
    phonics: "首音节读 /feɪ/，英式拼写 favourite 保留 u。",
    example: "What is your favourite subject at school?",
    translation: "你在学校最喜欢哪门课？",
  },
  {
    id: 17,
    category: "学习与能力",
    word: "improve",
    ipa: "/ɪmˈpruːv/",
    partOfSpeech: "v.",
    meaning: "提高；改善",
    syllables: ["im", "prove"],
    stress: "重音在第二音节 prove",
    phonics: "词尾 ove 在这个词中读 /uːv/，需要整体记忆。",
    example: "Reading every day will improve your English.",
    translation: "每天阅读会提高你的英语水平。",
  },
  {
    id: 18,
    category: "学习与能力",
    word: "independent",
    ipa: "/ˌɪndɪˈpendənt/",
    partOfSpeech: "adj.",
    meaning: "独立的；自主的",
    syllables: ["in", "de", "pen", "dent"],
    stress: "主重音在第三音节 pen",
    phonics: "三个 e 的读音不同，重读的 pen 中 e 读 /e/。",
    example: "The course helps students become independent learners.",
    translation: "这门课程帮助学生成为自主学习者。",
  },
  {
    id: 19,
    category: "学习与能力",
    word: "information",
    ipa: "/ˌɪnfəˈmeɪʃən/",
    partOfSpeech: "n.",
    meaning: "信息；资料",
    syllables: ["in", "for", "ma", "tion"],
    stress: "主重音在第三音节 ma",
    phonics: "重读 a 读 /eɪ/，tion 读 /ʃən/。",
    example: "You can find more information on the website.",
    translation: "你可以在网站上找到更多信息。",
  },
  {
    id: 20,
    category: "旅行与活动",
    word: "journey",
    ipa: "/ˈdʒɜːni/",
    partOfSpeech: "n.",
    meaning: "旅程",
    syllables: ["jour", "ney"],
    stress: "重音在第一音节 jour",
    phonics: "j 读 /dʒ/，our 在这个词中读长音 /ɜː/。",
    example: "The train journey took nearly three hours.",
    translation: "火车旅程用了将近三个小时。",
  },
  {
    id: 21,
    category: "生活与环境",
    word: "necessary",
    ipa: "/ˈnesəsəri/",
    partOfSpeech: "adj.",
    meaning: "必要的",
    syllables: ["nec", "es", "sar", "y"],
    stress: "重音在第一音节 nec",
    phonics: "c 在 e 前读 /s/；记忆拼写：一个 c，两个 s。",
    example: "A passport is necessary for this journey.",
    translation: "这次旅行必须携带护照。",
  },
  {
    id: 22,
    category: "旅行与活动",
    word: "opportunity",
    ipa: "/ˌɒpəˈtjuːnəti/",
    partOfSpeech: "n.",
    meaning: "机会",
    syllables: ["op", "por", "tu", "ni", "ty"],
    stress: "主重音在第三音节 tu",
    phonics: "重读 tu 在英音中常读 /tjuː/，词尾 ty 读 /ti/。",
    example: "The trip was a good opportunity to practise English.",
    translation: "这次旅行是练习英语的好机会。",
  },
  {
    id: 23,
    category: "旅行与活动",
    word: "organise",
    ipa: "/ˈɔːɡənaɪz/",
    partOfSpeech: "v.",
    meaning: "组织；安排",
    syllables: ["or", "gan", "ise"],
    stress: "重音在第一音节 or",
    phonics: "英式拼写常用 ise，词尾读 /aɪz/。",
    example: "We are organising a school concert.",
    translation: "我们正在组织一场校园音乐会。",
  },
  {
    id: 24,
    category: "日常交流",
    word: "probably",
    ipa: "/ˈprɒbəbli/",
    partOfSpeech: "adv.",
    meaning: "很可能；大概",
    syllables: ["prob", "a", "bly"],
    stress: "重音在第一音节 prob",
    phonics: "中间 a 弱读 /ə/，词尾 bly 连读为 /bli/。",
    example: "I will probably finish the book tonight.",
    translation: "我今晚很可能会读完这本书。",
  },
  {
    id: 25,
    category: "日常交流",
    word: "recommend",
    ipa: "/ˌrekəˈmend/",
    partOfSpeech: "v.",
    meaning: "推荐；建议",
    syllables: ["rec", "om", "mend"],
    stress: "主重音在第三音节 mend",
    phonics: "重读闭音节 mend 中 e 读 /e/，拼写含双 m。",
    example: "Can you recommend a good film for children?",
    translation: "你能推荐一部适合儿童的好电影吗？",
  },
  {
    id: 26,
    category: "感受与责任",
    word: "responsible",
    ipa: "/rɪˈspɒnsəbəl/",
    partOfSpeech: "adj.",
    meaning: "负责的；有责任心的",
    syllables: ["re", "spon", "si", "ble"],
    stress: "重音在第二音节 spon",
    phonics: "重读 o 在英音中读 /ɒ/，词尾 ble 读 /bəl/。",
    example: "Each student is responsible for one task.",
    translation: "每名学生负责一项任务。",
  },
  {
    id: 27,
    category: "感受与责任",
    word: "surprised",
    ipa: "/səˈpraɪzd/",
    partOfSpeech: "adj.",
    meaning: "惊讶的",
    syllables: ["sur", "prised"],
    stress: "重音在第二音节 prised",
    phonics: "i_e 读 /aɪ/，词尾 ed 在浊音后读 /d/。",
    example: "I was surprised by the size of the museum.",
    translation: "博物馆的规模让我很惊讶。",
  },
  {
    id: 28,
    category: "生活与环境",
    word: "traditional",
    ipa: "/trəˈdɪʃənəl/",
    partOfSpeech: "adj.",
    meaning: "传统的",
    syllables: ["tra", "di", "tion", "al"],
    stress: "重音在第二音节 di",
    phonics: "tion 读 /ʃən/，词尾 al 常弱读 /əl/。",
    example: "They served traditional food at the festival.",
    translation: "节日上他们提供了传统食物。",
  },
  {
    id: 29,
    category: "日常交流",
    word: "usually",
    ipa: "/ˈjuːʒuəli/",
    partOfSpeech: "adv.",
    meaning: "通常",
    syllables: ["u", "su", "al", "ly"],
    stress: "重音在第一音节 u",
    phonics: "词首 u 读 /juː/，中间 s 在这里读 /ʒ/。",
    example: "I usually take the bus to school.",
    translation: "我通常乘公交车上学。",
  },
  {
    id: 30,
    category: "旅行与活动",
    word: "volunteer",
    ipa: "/ˌvɒlənˈtɪə/",
    partOfSpeech: "n./v.",
    meaning: "志愿者；自愿做",
    syllables: ["vol", "un", "teer"],
    stress: "主重音在第三音节 teer",
    phonics: "词尾 eer 在英音中读 /ɪə/。",
    example: "She works as a volunteer at the animal centre.",
    translation: "她在动物中心做志愿者。",
  },
];

export const PET_CATEGORIES: PetCategory[] = ["学习与能力", "旅行与活动", "日常交流", "生活与环境", "感受与责任"];

export const PET_STUDY_WORDS = PET_CATEGORIES.flatMap((category) => PET_WORDS.filter((word) => word.category === category));

export const PET_READING = {
  title: "A Different Kind of School Trip",
  paragraphs: [
    "Last month, our class had the opportunity to visit a local wildlife centre. Before the journey, our teacher asked us to organise three small teams.",
    "At the centre, a volunteer gave us information about the animals and explained why a clean environment is necessary for them. I was surprised by how much work the team did every day.",
    "The experience helped us understand responsible behaviour. Although the weather was cold, everyone enjoyed the adventure and agreed to recommend the centre to other students.",
  ],
  translation: "上个月，我们班有机会参观当地的野生动物中心。出发前，老师让我们组织三个小组。中心的志愿者介绍了动物的资料，并解释了清洁环境的重要性。这次经历让我们理解了负责任的行为。虽然天气寒冷，但大家都很喜欢这次活动。",
  focusWords: ["opportunity", "journey", "organise", "volunteer", "information", "environment", "necessary", "surprised", "experience", "responsible", "although", "adventure", "recommend"],
};
