import { useEffect, useRef, useState } from "react";
import { correctAnswer, dateKey, DIMENSIONS, EXERCISES, firstResults, freshPrep, markExercise, PHRASES, readPrepBackup, reportText, SPEAKING_TASKS, unresolvedQuestions, validPrep, weekDays, type Exercise, type ManualRecord, type PrepState, type Result, type Skill } from "./preparation-data";
import { speak, stopSpeech } from "./pet-speech";
import { CourseView } from "./course-view";
import "./writing.css";
import "./preparation.css";

type Panel = "plan" | "vocab" | "grammar" | "composition" | "reading" | "listening" | "speaking" | "mistakes" | "mock" | "parent";
const PANELS: Array<[Panel, string, string]> = [["plan", "诊断与计划", "时间安排 · 逐科摸底"], ["vocab", "词汇与短语", "主题搭配 · 四项能力"], ["grammar", "语法与句子", "讲解 · 练习 · 运用"], ["composition", "写作表达课", "句型 · 段落 · 手工点评"], ["reading", "阅读训练", "六类题型 · 答案依据"], ["listening", "听力训练", "四类题型 · 精听复盘"], ["speaking", "口语训练", "四个环节 · 手工点评"], ["mistakes", "全科错题", "错因 · 重做 · 复查"], ["mock", "模拟与记录", "合法材料 · 人工记录"], ["parent", "家长复盘", "学习报告 · 材料 · 备份"]];
const SKILL_NAMES: Record<Skill, string> = { grammar: "语法", reading: "阅读", listening: "听力" };
const CAUSES = ["待分析", "词汇或搭配", "语法", "漏看限制条件", "同义替换", "被干扰信息影响", "听不清连读", "数字日期或拼写", "时间不足"];
type Update = (change: (state: PrepState) => PrepState) => boolean;
function downloadPrep(name: string, text: string, type = "text/plain;charset=utf-8"): void { const url = URL.createObjectURL(new Blob([text], { type })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 10000); }

export function PreparationView({ username, onNavigate, initialPanel = "plan" }: { username: string; onNavigate: (tab: "writing" | "library" | "reading") => void; initialPanel?: "plan" | "composition" }) {
  const key = `pet-preparation-v1-${username}`;
  const [loaded] = useState(() => { try { const raw = localStorage.getItem(key); const data: unknown = raw ? JSON.parse(raw) : freshPrep(); if (!validPrep(data)) throw new Error("本机备考记录格式异常，请导出原始记录并保留备份后处理。"); return { raw, data, error: "" }; } catch (error) { return { raw: null, data: freshPrep(), error: String(error) }; } });
  const baseline = useRef(loaded.raw);
  const [state, setState] = useState(loaded.data);
  const [message, setMessage] = useState(loaded.error);
  const [panel, setPanel] = useState<Panel>(initialPanel);
  const [selected, setSelected] = useState("");
  const update: Update = change => {
    try {
      if (loaded.error) throw new Error(loaded.error);
      if (localStorage.getItem(key) !== baseline.current) throw new Error("其他标签页已修改备考记录，请刷新后继续。当前操作尚未保存。");
      const next = change(state);
      if (!validPrep(next)) throw new Error("内容过长或记录已达上限（500 次练习、300 条手工记录），请先导出备份再整理。学习时间须为 15 至 240 分钟。");
      const raw = JSON.stringify(next); localStorage.setItem(key, raw); baseline.current = raw; setState(next); setMessage("已保存到本机"); return true;
    } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败，请检查浏览器存储空间。"); return false; }
  };
  const go = (next: Panel, exerciseId = "") => { stopSpeech(); setSelected(exerciseId); setPanel(next); };
  const backup = () => downloadPrep(`PET-preparation-${username}-${dateKey()}.json`, JSON.stringify({ kind: "pet-preparation", version: 1, username, data: state }, null, 2), "application/json");
  return <div className="pet-page pet-writing pet-prep">
    <header><span className="pet-eyebrow">PET · 学习工作台</span><h1>备考中心</h1><p>从诊断到复习，每科都有入口。先做原创小练习，再用合法材料检验完整考试能力。</p></header>
    <p className="pet-writing-notice">不接入 AI，不自动评分写作或口语。这里的计划、练习和手工点评仅保存在当前账号的本机浏览器；请定期导出备份。写作另有独立备份。</p>
    <nav className="pet-prep-menu" aria-label="备考模块">{PANELS.map(([id, title, detail]) => <button key={id} aria-pressed={panel === id} onClick={() => go(id)}><strong>{title}</strong><small>{detail}</small></button>)}<button onClick={() => onNavigate("writing")}><strong>写作训练</strong><small>原稿 · 照片 · 点评 · 修改稿</small></button></nav>
    <p role="status" className="pet-prep-status">{message}</p>
    {panel === "plan" && <Plan state={state} update={update} go={go} onWriting={() => onNavigate("writing")} />}
    {panel === "vocab" && <Vocabulary state={state} update={update} onLibrary={() => onNavigate("library")} />}
    {(panel === "grammar" || panel === "composition") && <CourseView key={panel} kind={panel === "grammar" ? "grammar" : "writing"} work={state.lessons ?? {}} onSave={(id, work) => update(s => ({ ...s, lessons: { ...s.lessons, [id]: work } }))} onWriting={() => onNavigate("writing")} />}
    {panel === "parent" && <p>课程进度：{Object.values(state.lessons ?? {}).filter(w => w.submitted).length} 课已提交，{Object.values(state.lessons ?? {}).filter(w => w.reviewed).length} 课已手工复查。课程答案、原稿、点评和修改稿包含在备考 JSON 备份中；单课点评材料在课程页导出。</p>}
    {(["grammar", "reading", "listening"] as string[]).includes(panel) && <section><h2>{SKILL_NAMES[panel as Skill]}训练</h2><p>以下均为原创入门练习，覆盖题型思路，数量和难度不足以作为完整真题或水平定级。</p>{panel === "reading" && <button onClick={() => onNavigate("reading")}>打开精读与材料导入</button>}{panel === "listening" && <><p>合成语音用于基础听辨，不能替代真人语速、口音与多人交流训练。</p><button onClick={() => onNavigate("reading")}>打开官方听力材料与精听</button></>}
      <div className="pet-writing-actions">{EXERCISES.filter(e => e.skill === panel).map(e => <button key={e.id} aria-pressed={selected === e.id} onClick={() => setSelected(e.id)}>{e.title}</button>)}</div>
      {EXERCISES.filter(e => e.id === selected && e.skill === panel).map(e => <Quiz key={e.id} exercise={e} onSave={result => update(s => ({ ...s, results: [...s.results, result] }))} />)}
    </section>}
    {panel === "speaking" && <Speaking state={state} update={update} username={username} />}
    {panel === "mistakes" && <Mistakes state={state} update={update} go={go} />}
    {panel === "mock" && <section><h2>模拟与记录</h2><p>先使用官方免费样题或已购买的正版材料。本站小练习不拼成“完整模考”，也不推算通过率。</p><p>记录材料名称、日期、是否首次使用、各部分实际用时、阅读/听力答对数与总题数，以及写作/口语的人工点评。题目做过要标明，避免把记住答案当作能力提升。</p><a href="https://www.cambridgeenglish.org/exams-and-tests/qualifications/preliminary/preparation/" target="_blank" rel="noreferrer">Cambridge 官方备考材料</a><ManualForm kind="mock" title="新增模考记录" update={update} placeholder="材料：\n是否首次使用：\n阅读：答对数 / 总题数，用时\n听力：答对数 / 总题数，用时\n写作：完成情况、待改进点\n口语：搭档、录音文件名、待改进点\n下周调整：" /><Records records={state.records.filter(r => r.kind === "mock")} update={update} /></section>}
    {panel === "parent" && <section><h2>家长复盘与材料</h2><p>每周花 10 分钟看首次作答、重复错误和完成情况。先问孩子卡在哪里，再决定下周重点；不以单次正确率贴水平标签。</p><label>现有合法材料与家长待办<textarea maxLength={5000} value={state.resources} onChange={e => update(s => ({ ...s, resources: e.target.value }))} /></label><ul><li>KET 成绩出来后记录分项成绩；具体考试日期确认后补填。</li><li>提供教材名称、可使用范围和近期学校语法内容；未购买时先用官方免费资源与原创题。</li><li>写作保留独立原稿、实际用时和帮助情况；口语保留原始录音。</li><li>把题目、原稿/录音和导出的材料发到当前对话，收到点评后手动粘贴回对应记录。</li></ul><pre className="pet-prep-report">{reportText(username, state)}</pre><div className="pet-writing-actions"><button onClick={() => downloadPrep(`PET-review-${dateKey()}.txt`, reportText(username, state))}>导出复盘与点评材料</button><button onClick={backup}>导出备考备份</button></div><label>恢复备考备份（替换当前备考记录）<input type="file" accept=".json,application/json" onChange={async e => { const file = e.target.files?.[0]; e.target.value = ""; if (!file) return; try { if (file.size > 4_000_000) throw new Error("备份超过大小限制。"); const data = readPrepBackup(await file.text(), username); if (!window.confirm("恢复将替换当前备考记录。建议先导出当前备份。继续吗？")) return; update(() => data); } catch (error) { setMessage(error instanceof Error ? error.message : "恢复失败"); } }} /></label><p>备份包含计划、短语标记、客观题记录、课程原稿与修改稿和手工点评；不含写作照片、录音或精读材料，请分别保存。</p>{loaded.error && <button onClick={() => { try { downloadPrep("PET-preparation-recovery.txt", localStorage.getItem(key) ?? ""); } catch { setMessage("无法访问浏览器存储，请保留此页面。"); } }}>导出原始记录</button>}</section>}
  </div>;
}

function Plan({ state, update, go, onWriting }: { state: PrepState; update: Update; go: (panel: Panel, id?: string) => void; onWriting: () => void }) {
  const first = firstResults(state.results);
  const rotations = ["语法与句子", "阅读训练", "听力训练", "写作训练", "口语训练", "综合练习与精读", "错题重做与家长复盘"];
  return <section><h2>诊断与学习计划</h2><p>已知信息：11 岁、KET 成绩待公布；一篇邮件在 20 分钟内独立完成，家长未修改。口语未录，暂不判断口语水平。</p><div className="pet-writing-grid"><label>目标考试月份<input type="month" value={state.examMonth} onChange={e => { if (e.target.value) update(s => ({ ...s, examMonth: e.target.value, examDate: "" })); }} /></label><label>具体考试日期（待确认可留空）<input type="date" value={state.examDate} onChange={e => update(s => ({ ...s, examDate: e.target.value, examMonth: e.target.value ? e.target.value.slice(0, 7) : s.examMonth }))} /></label><label>平日每天分钟数<input type="number" min={15} max={240} defaultValue={state.weekdayMinutes} onBlur={e => { if (!update(s => ({ ...s, weekdayMinutes: Number(e.target.value) }))) e.target.value = String(state.weekdayMinutes); }} /></label><label>周末每天分钟数<input type="number" min={15} max={240} defaultValue={state.weekendMinutes} onBlur={e => { if (!update(s => ({ ...s, weekendMinutes: Number(e.target.value) }))) e.target.value = String(state.weekendMinutes); }} /></label></div><p>暂按周六、周日各 120 分钟安排；若“两小时”指周末合计，请把周末每天改为 60 分钟。计划可调整，漏做不会自动堆到第二天。</p><label>KET 成绩与分项记录<input maxLength={5000} value={state.ket} onChange={e => update(s => ({ ...s, ket: e.target.value }))} /></label><label>本周薄弱项与调整<textarea maxLength={5000} value={state.priority} onChange={e => update(s => ({ ...s, priority: e.target.value }))} /></label>
    <h3>首次诊断记录</h3><p>各科先选一组独立完成，并记录是否看过讲解。这里显示第一次提交；重做不覆盖诊断。样本少时只用于发现问题。</p><div className="pet-prep-menu">{(["grammar", "reading", "listening"] as Skill[]).map(skill => { const rows = first.filter(r => EXERCISES.find(e => e.id === r.exerciseId)?.skill === skill); return <button key={skill} onClick={() => go(skill, EXERCISES.find(e => e.skill === skill)?.id)}><strong>{SKILL_NAMES[skill]}</strong><small>{rows.length ? `${rows.reduce((n,r) => n+r.correct,0)} / ${rows.reduce((n,r) => n+r.total,0)} 题 · ${rows.length} 组首次记录` : "尚未作答"}</small></button>; })}<button onClick={onWriting}>写作原稿与手工点评</button><button onClick={() => go("speaking")}>口语诊断与录音材料</button></div>
    <h3>本周安排</h3><div className="pet-prep-week">{weekDays().map((day, i) => { const key = dateKey(day); const minutes = i < 5 ? state.weekdayMinutes : state.weekendMinutes; const words = Math.round(minutes / 4); const review = Math.round(minutes / 6); return <article key={key}><strong>{key} · {"一二三四五六日"[i]}</strong><p>{rotations[i]}</p><small>词汇 {words} 分钟 + 重点 {minutes-words-review} 分钟 + 复盘 {review} 分钟。周末分段完成，中间休息。</small><label className="pet-writing-check"><input type="checkbox" checked={!!state.completed[key]} onChange={e => update(s => ({ ...s, completed: { ...s.completed, [key]: e.target.checked } }))} />已完成当日安排</label></article>; })}</div><p>需要补做时，在“本周薄弱项与调整”写明换到哪一天；优先保留复盘，不补双倍任务。</p>
  </section>;
}

function Quiz({ exercise, onSave }: { exercise: Exercise; onSave: (result: Result) => boolean }) {
  const [answers, setAnswers] = useState<Record<string, string>>({}); const [submitted, setSubmitted] = useState<Result | null>(null); const [mode, setMode] = useState<"practice" | "check">("practice"); const [started, setStarted] = useState(0); const [seconds, setSeconds] = useState(0); const [plays, setPlays] = useState(0); const [playing, setPlaying] = useState(false); const [audioMessage, setAudioMessage] = useState(""); const [showScript, setShowScript] = useState(false); const [application, setApplication] = useState("");
  const active = started > 0 && !submitted;
  useEffect(() => { if (!active) return; const timer = setInterval(() => setSeconds(Math.floor((Date.now() - started) / 1000)), 1000); return () => clearInterval(timer); }, [active, started]);
  useEffect(() => () => stopSpeech(), []);
  const play = () => { setPlaying(true); setPlays(n => n+1); setAudioMessage(""); speak(exercise.text, 1, { systemOnly: true, onEnd: () => setPlaying(false), onCancel: () => setPlaying(false), onError: message => { setPlaying(false); setPlays(n => Math.max(0,n-1)); setAudioMessage(message); } }); };
  const finish = () => { const result: Result = { id: crypto.randomUUID(), exerciseId: exercise.id, at: new Date().toISOString(), seconds: Math.floor((Date.now()-started)/1000), mode, answers, correct: markExercise(exercise, answers), total: exercise.questions.length, causes: {} }; if (onSave(result)) { stopSpeech(); setSubmitted(result); setSeconds(result.seconds); } };
  return <article className="pet-writing-practice"><h3>{exercise.title}</h3><p>{exercise.instruction}</p><p>建议 {exercise.minutes} 分钟 · {exercise.questions.length} 题</p>{!started && <><label>练习模式<select value={mode} onChange={e => setMode(e.target.value as "practice" | "check")}><option value="practice">学习模式（可看讲解，听力可反复播放）</option><option value="check">独立检查（隐藏讲解，听力最多两次）</option></select></label><button className="pet-writing-primary" onClick={() => setStarted(Date.now())}>开始计时作答</button></>}
    {!!started && <><p role="timer">用时 {Math.floor(seconds/60)} 分 {seconds%60} 秒{seconds > exercise.minutes*60 ? " · 已超过建议时间，可继续完成" : ""}</p>{exercise.skill === "listening" ? <><div className="pet-writing-actions"><button disabled={playing || (!submitted && mode === "check" && plays >= 2)} onClick={play}>播放听力（已播放 {plays} 次）</button><button disabled={!playing} onClick={() => stopSpeech()}>停止播放</button>{(mode === "practice" || submitted) && <button onClick={() => setShowScript(v => !v)}>{showScript ? "隐藏原文" : "显示原文进行精听"}</button>}</div><p role="status">{audioMessage}</p>{showScript && <p className="pet-prep-text" lang="en">{exercise.text}</p>}</> : (exercise.skill !== "grammar" || mode === "practice" || submitted) && <p className="pet-prep-text" lang="en">{exercise.text}</p>}
      {exercise.questions.map((item, index) => <fieldset className="pet-writing-practice" key={item.id} disabled={!!submitted}><legend>{index+1}. {item.prompt}</legend>{item.choices ? item.choices.map(choice => <label key={choice}><input type="radio" name={item.id} value={choice} checked={answers[item.id] === choice} onChange={() => setAnswers(a => ({ ...a, [item.id]: choice }))} />{choice}</label>) : <input aria-label={item.prompt} maxLength={100} autoComplete="off" value={answers[item.id] ?? ""} onChange={e => setAnswers(a => ({ ...a, [item.id]: e.target.value }))} />}{submitted && <div className="pet-prep-explanation"><strong>{correctAnswer(answers[item.id] ?? "", item.answer) ? "正确" : `需复习 · 正确答案：${item.answer}`}</strong><p>依据：{item.evidence}</p><p>{item.explanation}</p></div>}</fieldset>)}
      {!submitted ? <><p>未作答题目按错误记录。切换模块会丢失尚未提交的答题内容，请先完成提交。</p><button onClick={finish}>提交并查看解析</button></> : <><p role="status">本次 {submitted.correct} / {submitted.total} 题正确，已保存。错题可在“全科错题”记录原因并重做。</p>{exercise.apply && <><label>迁移练习：{exercise.apply}<textarea value={application} onChange={e => setApplication(e.target.value)} /></label><p>此草稿不自动保存；导出后发到对话手工点评，也可将句子用于写作任务。</p><button onClick={() => downloadPrep(`PET-sentence-${exercise.id}.txt`, `${exercise.title}\n任务：${exercise.apply}\n我的句子：${application}`)}>导出句子点评材料</button></>}<button onClick={() => { stopSpeech(); setAnswers({}); setSubmitted(null); setStarted(0); setSeconds(0); setPlays(0); setShowScript(false); }}>重新练习（保留本次记录）</button></>}
    </>}
  </article>;
}

function Vocabulary({ state, update, onLibrary }: { state: PrepState; update: Update; onLibrary: () => void }) {
  const [theme, setTheme] = useState("School"); const [spelling, setSpelling] = useState<Record<string,string>>({}); const [checked, setChecked] = useState<Record<string,boolean>>({});
  useEffect(() => () => stopSpeech(), []);
  return <section><h2>词汇与短语</h2><p>首批 12 个主题短语作为搭配练习，与现有词库配合使用。四项标记为人工确认，不等同于测评成绩。</p><button onClick={onLibrary}>打开完整词库与复习</button><label>主题<select value={theme} onChange={e => setTheme(e.target.value)}>{[...new Set(PHRASES.map(p => p[0]))].map(t => <option key={t}>{t}</option>)}</select></label>{PHRASES.filter(p => p[0] === theme).map(([,phrase,meaning,example,note]) => <article className="pet-writing-practice" key={phrase}><h3>{meaning}</h3><button onClick={() => speak(phrase, 0.85, { systemOnly: true })}>听短语</button><label>凭记忆拼写：{meaning}<input autoComplete="off" value={spelling[phrase] ?? ""} onChange={e => { setSpelling(s => ({ ...s,[phrase]:e.target.value })); setChecked(c => ({ ...c,[phrase]:false })); }} /></label><button onClick={() => setChecked(c => ({ ...c,[phrase]:true }))}>检查拼写</button>{checked[phrase] && <p role="status">{correctAnswer(spelling[phrase] ?? "", phrase) ? "拼写正确" : `再记一次：${phrase}`}</p>}<details><summary>查看短语、例句与易混点</summary><p lang="en"><strong>{phrase}</strong><br />{example}</p><p>{note}</p></details><div className="pet-writing-actions">{DIMENSIONS.map(d => { const key = `${phrase}:${d}`; return <label className="pet-writing-check" key={d}><input type="checkbox" checked={!!state.phraseChecks[key]} onChange={e => update(s => ({ ...s, phraseChecks: { ...s.phraseChecks,[key]:e.target.checked } }))} />{d}</label>; })}</div><p>勾选“会使用”前，先独立口述或写出一个与自己有关的新句子。未掌握的维度留空，下次优先复习。</p></article>)}</section>;
}

function ManualForm({ kind, title, update, placeholder, initialTitle = "" }: { kind: ManualRecord["kind"]; title: string; update: Update; placeholder: string; initialTitle?: string }) {
  const [name, setName] = useState(initialTitle); const [text, setText] = useState(""); const [feedback, setFeedback] = useState("");
  return <form className="pet-writing-practice" onSubmit={e => { e.preventDefault(); if (!name.trim() || !text.trim()) return; if (update(s => ({ ...s, records: [...s.records, { id: crypto.randomUUID(), kind, title:name.trim(), text, feedback, resolved:false, at:new Date().toISOString() }] }))) { setName(initialTitle); setText(""); setFeedback(""); } }}><h3>{title}</h3><label>记录标题<input required maxLength={200} value={name} onChange={e => setName(e.target.value)} /></label><label>原始表现与材料<textarea required maxLength={10000} placeholder={placeholder} value={text} onChange={e => setText(e.target.value)} /></label><label>手工点评（可稍后填写）<textarea maxLength={10000} value={feedback} onChange={e => setFeedback(e.target.value)} /></label><button className="pet-writing-primary" type="submit">保存这条记录</button></form>;
}
function Records({ records, update }: { records: ManualRecord[]; update: Update }) {
  return <div>{[...records].reverse().map(record => <article key={record.id} className="pet-writing-practice"><h3>{record.title}</h3><small>{new Date(record.at).toLocaleString()}</small><p className="pet-prep-text">{record.text}</p><label>点评与复查：{record.title}<textarea maxLength={10000} value={record.feedback} onChange={e => update(s => ({ ...s, records:s.records.map(r => r.id === record.id ? { ...r,feedback:e.target.value } : r) }))} /></label><label className="pet-writing-check"><input type="checkbox" checked={record.resolved} onChange={e => update(s => ({ ...s, records:s.records.map(r => r.id === record.id ? { ...r,resolved:e.target.checked } : r) }))} />已完成复查</label><button onClick={() => downloadPrep(`PET-manual-${record.id}.txt`, `记录编号：${record.id}\n任务：${record.title}\n原始表现：${record.text}\n已有点评：${record.feedback}\n请按任务完成情况、表达清楚程度、语言问题和下次练习建议点评；材料不足时说明，不推算考试分数。`)}>导出这条点评材料</button></article>)}</div>;
}
function Speaking({ state, update, username }: { state: PrepState; update: Update; username: string }) {
  const [part, setPart] = useState(0); const [audio, setAudio] = useState<{ url:string; name:string } | null>(null); const [error, setError] = useState(""); const [seconds, setSeconds] = useState(0); const [running, setRunning] = useState(false);
  useEffect(() => { if (!running) return; const timer=setInterval(() => setSeconds(s=>s+1),1000); return () => clearInterval(timer); }, [running]);
  useEffect(() => () => { if (audio) URL.revokeObjectURL(audio.url); }, [audio]);
  const task = SPEAKING_TASKS[part];
  return <section><h2>口语训练与手工点评</h2><p>手机录音即可，不需要开通 AI。录下完整题目和孩子的独立回答，记录准备时间及家长提示情况。</p><label>口语环节<select value={part} onChange={e => { setPart(Number(e.target.value)); setSeconds(0); setRunning(false); }}>{SPEAKING_TASKS.map((t,i)=><option key={t.title} value={i}>{t.title}</option>)}</select></label><p lang="en" className="pet-prep-text">{task.prompt}</p><p>{task.guide}</p><p role="timer">练习用时 {Math.floor(seconds/60)} 分 {seconds%60} 秒 · 本次建议 {task.minutes} 分钟（训练用，不代表完整考试时长）</p><div className="pet-writing-actions"><button onClick={()=>setRunning(v=>!v)}>{running?"暂停计时":"开始/继续计时"}</button><button onClick={()=>{setSeconds(0);setRunning(false);}}>重置计时</button><button onClick={()=>downloadPrep(`PET-speaking-${username}-part${part+1}.txt`, `${task.title}\n题目：${task.prompt}\n说明：${task.guide}\n本次计时：${seconds} 秒\n录音文件：${audio?.name ?? "请另附原始录音"}\n独立完成：\n准备时间：\n家长提示：\n请人工点评任务回应、组织、语法词汇、可理解度；合作任务另看互动，不能仅凭文本判断发音。`)}>导出口语任务与点评单</button></div><label>选择录音试听（不上传、不保存到应用）<input type="file" accept="audio/*,.m4a,.mp3,.wav,.webm" onChange={e=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;if(file.size>50*1024*1024 || !(file.type.startsWith("audio/") || /\.(m4a|mp3|wav|webm)$/i.test(file.name))){setError("请选择不超过 50 MB 的音频文件。");return;}setAudio({url:URL.createObjectURL(file),name:file.name});setError("");}} /></label>{audio && <div><p>{audio.name}</p><audio key={audio.url} controls src={audio.url} onError={()=>setError("浏览器无法播放此格式；可用手机播放原文件，或转为 MP3 后试听。")} /></div>}<p role="status">{error}</p><p>退出模块后需重新选择录音。原始文件由家长保管，导出的点评单不含声音；发到对话时请把录音一并附上。</p><ManualForm key={part} kind="speaking" title="记录本次口语表现" initialTitle={task.title} update={update} placeholder={`题目：${task.prompt}\n录音文件名：\n独立完成与提示情况：\n实际用时：\n孩子觉得困难的地方：`} /><Records records={state.records.filter(r=>r.kind==="speaking")} update={update} /></section>;
}
function Mistakes({ state, update, go }: { state: PrepState; update: Update; go: (panel: Panel, id?: string) => void }) {
  const wrong = unresolvedQuestions(state.results);
  return <section><h2>全科错题与复查</h2><p>客观题按每组最近一次提交判断是否仍需复习；首次诊断记录保留不变。写作、口语和外部材料的问题可手工登记。</p>{!wrong.length && <p>暂无待复习客观题。尚未练习的题目不视为已掌握。</p>}{wrong.map(({exercise,question,result})=><article key={question.id} className="pet-writing-practice"><h3>{exercise.title}</h3><p>{question.prompt}</p><p>我的答案：{result.answers[question.id] || "未作答"} · 正确答案：{question.answer}</p><p>依据：{question.evidence}</p><p>{question.explanation}</p><label>错因：{question.id}<select value={result.causes[question.id] ?? "待分析"} onChange={e=>update(s=>({...s,results:s.results.map(r=>r.id===result.id?{...r,causes:{...r.causes,[question.id]:e.target.value}}:r)}))}>{CAUSES.map(c=><option key={c}>{c}</option>)}</select></label><button onClick={()=>go(exercise.skill,exercise.id)}>重新练习这一组</button></article>)}<ManualForm kind="mistake" title="新增写作、口语或其他错题" update={update} placeholder="科目与来源：\n题目要求：\n原始回答：\n错误原因：\n正确表达与依据：\n下次复查日期：" /><Records records={state.records.filter(r=>r.kind==="mistake")} update={update} /></section>;
}
